### ISSUE TITLE
testing: add integration testing that asserts STUN/NAT hole punching is working properly

### ISSUE THREAD

**Issue by backkem** [pion/ice#27] opened 2018-07-18 19:51 UTC
Investigate ways to simulate and test traversal of different NAT types and combinations of NAT types.

Related:

- libp2p/go-libp2p#111

**Comment by Sean-Der** [comment] 2019-06-25 08:27
@enobufs you ok with me closing this as a `dupe` of your vnet work? I think everything will be covered when that rolls out.

We can simulate all NAT types between peers (and that we get the expected behavior) so I think that covers everything!

**Comment by enobufs** [comment] 2019-06-25 23:41
Yes, I'd agree. Let me close this issue.
Related: pion/webrtc#712

**Closed by enobufs** 2019-06-25 23:41 UTC
Labels: triaged
