### ISSUE TITLE
udp-mux: RemoveConnByUfrag removes existing connection when having 1:1 NAT mapping

### ISSUE THREAD

**Issue by m1k1o** [pion/ice#505] opened 2022-12-08 22:32 UTC
In recent commit https://github.com/pion/ice/commit/7f13fd1947277496282a32bd7bffcbd21bb02247 closing connection on duplicate candidates has been added.

E.g. we have 2 `localAddresses`, and `extIPMapper` as `CandidateTypeHost` with `ipSole`. This means, both of our local addresses will be overwritten with a single IP, here:
https://github.com/pion/ice/blob/ea00dc7424d06d6ed4c642639d59bcdf41156d0a/gather.go#L284-L291

When we continue [adding candidate](https://github.com/pion/ice/blob/ea00dc7424d06d6ed4c642639d59bcdf41156d0a/gather.go#L310), we check inside for duplicates. It adds first candidate and when processing second candidate, [it notices](https://github.com/pion/ice/blob/ea00dc7424d06d6ed4c642639d59bcdf41156d0a/agent.go#L825), there is already existing candidate with given addr so attempts to close it.

After closing candidate we do not need, [this cleanup task](https://github.com/pion/ice/blob/ea00dc7424d06d6ed4c642639d59bcdf41156d0a/udp_mux.go#L150-L153) will be executed, that attempts to remove conn by ufrag. But since both connections shared the same ufrag, it removes the first connection instead.

For tcp_mux it is not an issue, because it is [identified by local host](https://github.com/pion/ice/blob/ea00dc7424d06d6ed4c642639d59bcdf41156d0a/tcp_mux.go#L172) as well.

I tried to implement [the same per-addr separation](https://github.com/pion/ice/files/10190227/udp_mux.go.txt) as there is for tcp_mux, but since udp works differently, i was not able to get reliably correct addr when reading packets. Easier solution would be just to add [duplicate check for udp_mux ips](https://github.com/pion/ice/commit/23d31f85061f826331cc017fc88ca767d7071ceb).

### Your environment.
  - Version: v2.2.12

**Comment by r1a2y3** [comment] 2022-12-14 06:53
Hi, I haven't try to reproduce your issue. In my opinion, you try to use 2 local address but only one external IP And you want to use udp mux??  Such as local ip (192.168.10.10 / 192.168.10.20, mulplex udp port 3000, they have the same external ip. [128.29.20.30])How does the inbound udp packet forwarded by 128.29.20.30:3000? which one should be the dst ip?
 I think it's  ambiguous for 128.29.20.30.

---------------------------------------------------------
By the way, I looked through issues because I found the multiudpmux can't works when the remote use multiudpmux too... Such as two sfu cascaded, but they all use one single udp port.

**Comment by r1a2y3** [comment] 2022-12-15 02:04
Thanks @m1k1o . Got it! Maybe a temporary workaround is to limit your candidates to certain specified range that you want to avoid it. I use the below code to specify candidates now.
```
        // se
        se := webrtc.SettingEngine{}
        se.SetICEMulticastDNSMode(ice.MulticastDNSModeDisabled)

        // handle candidates
        nw := vnet.NewNet(nil)
        if len(c.WebRTC.Candidates) > 0 {
                candidates := c.WebRTC.Candidates
                if ifs, err := nw.Interfaces(); err == nil {
                        for _, ifc := range ifs {
                                if addrs, err := ifc.Addrs(); err == nil {
                                        tmpIfc := vnet.NewInterface((net.Interface)(ifc.InterfaceBase))
                                        for _, c := range candidates {
                                                for _, addr := range addrs {
                                                        if strings.HasPrefix(addr.String(), c+"/") {
                                                                tmpIfc.AddAddr(addr)
                                                        }
                                                }
                                        }
                                        *ifc = *tmpIfc
                                }
                        }
                }
        }
        se.SetVNet(nw)

```

**Comment by cnderrauber** [comment] 2022-12-25 03:08
@m1k1o You can use MultiUDPMux (`NewMultiUDPMuxFromPort`) to listen on multiple interfaces for udp mux, then each muxed connection is managed by corresponding UDPMux, will not be closed incorrectly

**Comment by m1k1o** [comment] 2022-12-25 11:08
@cnderrauber yes, that actually fixes my issue. But this makes the change backwards incompatible, although it should still work the same way but only with deprecation warning.

**Closed** 2023-04-14 21:15 UTC
Labels: bug, mux
