### ISSUE TITLE
Panic when adding candidate 

### ISSUE THREAD

**Issue by m1k1o** [pion/ice#589] opened 2023-06-26 19:18 UTC
This panic is fairly rare, but in certain (yet unknown) circumstances it is more prevalent.

```
panic: runtime error: invalid memory address or nil pointer dereference	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe1758f]	

goroutine 6592 [running]:	
github.com/pion/ice/v2.(*Agent).addCandidate.func1({0xc0011adf90?, 0xc0011adf48?}, 0xc000004300?)	
	/go/pkg/mod/github.com/pion/ice/v2@v2.3.4/agent.go:798 +0x26f	
github.com/pion/ice/v2.(*Agent).taskLoop(0xc000004300)	
	/go/pkg/mod/github.com/pion/ice/v2@v2.3.4/agent.go:240 +0xc2	
created by github.com/pion/ice/v2.NewAgent	
	/go/pkg/mod/github.com/pion/ice/v2@v2.3.4/agent.go:363 +0xd92
```

**Comment by Sean-Der** [comment] 2023-06-27 20:48
@m1k1o It looks like `candidateConn` is nil? https://github.com/pion/ice/blob/master/agent.go#L817C1-L818C1

I think it would be worth adding a defensive `if candidateConn != nil` check

It would be nice to figure out why this is happening though!

**Comment by m1k1o** [comment] 2023-06-27 21:15
From my findings, I see that right before panic, the code is frozen for a couple of seconds (up to 10). Probably because of some TCP connection blocking when write buffer is full. When it finally unblocks, it is flooded with all messages at once and most likely ocurrs some race condition that leads to panic.

Last message seems to be `Ignore duplicate candidate: tcp4 host <ip>:0`, where the IP is NAT1TO1 of the server. The candidate is announced as `candidate:4225724578 1 tcp 1675624447 <ip> 0 typ host tcptype active`. I saw recent changes in the code about Active ICE TCP Candidates, but this is `v2.3.4` what should predate those changes. I might try to upgrade to latest version to see if it happens again.

**Comment by Sean-Der** [comment] 2023-06-28 03:03
That is a strange one! I think we might be able to reproduce this though. Can you create a TCP client that doesn't disconnect properly. Maybe as simple as connecting from phone then turning on Airplane mode?

I am very confident that `Active ICE TCP` changes will not have fixed this. This is the passive code.

**Comment by m1k1o** [comment] 2023-07-12 18:40
Simply connecting using TCP on mobile and truning on Airplane Mode did not cut it:

```
6:09PM WRN write error: write tcp 172.17.0.3:52100->192.168.1.186:58735: use of closed network connection module=webrtc submodule=pion subsystem=ice-tcp
6:09PM INF error reading streaming packet: read tcp 172.17.0.3:52100->192.168.1.186:58735: use of closed network connection module=webrtc submodule=pion subsystem=ice-tcp
6:09PM WRN error closing connection: close tcp 172.17.0.3:52100->192.168.1.186:58735: use of closed network connection module=webrtc submodule=pion subsystem=ice-tcp
6:09PM WRN Failed to read from candidate tcp4 host 192.168.1.38:52100: io: read/write on closed pipe module=webrtc peer_id=1 session_id=user submodule=pion subsystem=ice
6:09PM WRN Failed to discover mDNS candidate 14e7f6f2-8a05-4212-8024-e43a6032d72a.local: mDNS: connection is closed module=webrtc peer_id=1 session_id=user submodule=pion subsystem=ice
```

![image](https://github.com/pion/ice/assets/7534274/5aef0be1-a735-464b-8084-d8a8b33ea034)


I traced it back to [this commit](https://github.com/pion/ice/commit/1d502ca6ec1075a762339556a5734e4b4441c452#diff-892d4d29fb83b93012d0a97c1c2d8e133aaa4f787a92db1c5f54614408f20966R169), that added `connConfigs = append(connConfigs, connConfig{nil, 0, TCPTypeActive})`, where `nil` was passed down to `addCandidate`.

![image](https://github.com/pion/ice/assets/7534274/8217d4f2-b3c2-42b3-9420-8984d1515b2a)


It was since then reverted by and changed by you. Therefore I believe, upgrading to the latest should fix the issue.

**Comment by m1k1o** [comment] 2023-07-12 19:41
After upgrading pion/ice to `v2.3.9` i can confirm, that it does not panic anymore.

But actually I am not able to connect using UDPMux or TCPMux. Only using ephemeral UDP the connection is possible. It has something to to again with the fact, that my server has 2 interfaces (first for the Internet, other for Management) and I am connecting from Management. After disabling the other Interface, it works like a charm.

This is issue on its own, so maybe it should be extracted and this one closed.

**Comment by Sean-Der** [comment] 2024-08-15 19:04
Closing, no work to be done here!

**Closed by Sean-Der** 2024-08-15 19:04 UTC
Labels: bug
